### PR TITLE
Edits to chapter 2

### PR DESCRIPTION
**Pull request by pharpend**
I have so far edited about half of it.

I added a ton of footnotes, mostly because my content would break the flow.

### CODE REVIEW

**Comment by pharpend** [comment]
I removed the test file, it was to test @wei2912 's build system.

**Comment by ghost** [comment]
@pharpend I'm not ignoring this, but it's going to take a more significant portion of my time to look it over given @jesyspa 's expansion of content last night than I have right this second. I'll have feedback before I close down work for the day.

**Comment by ghost** [comment]
I'm not sure how to respond to the first paragraph--i don't know if it's location reflects what you want, or if that's more for convenience and you'd like to replace the first paragraph.

I'd like to see how 'lists' effect the layout in the text before deciding one way or another.

I don't feel like the line breaks added benefit the text.

**Comment by pharpend** [comment]
> I'm not sure how to respond to the first paragraph--i don't know if it's location reflects what you want, or if that's more for convenience and you'd like to replace the first paragraph.

The part called "my submission" was commented out, so you can ignore it. It's just something that I might want to put somewhere for the future.

I didn't change much of @jesyspa's work, I just added line breaks and corrected a few grammar errors.

> I'd like to see how 'lists' effect the layout in the text before deciding one way or another.

I'm not sure what you mean. Here's a scrot of the resulting PDF:



> I don't feel like the line breaks added benefit the text.

The shorter paragraphs make it easier to read. Remember, our goal is to make the book easy & fun to read, not to be "proper".

**Pull request merged**
