### PR TITLE
Manually add known host, because Travis doesn't do it for PRs.

### PR DESCRIPTION
**Pull request by wei2912**
This causes deploys to stall.

### CODE REVIEW

**Comment by pharpend** [comment]
> This causes deploys to stall.

Could you elaborate?

**Comment by wei2912** [comment]
Basically, the key isn't decrypted as Travis only allows decryption for commits to the repository itself. I believe this is a security measure. Hence, the deploys will be unable to proceed.

I will ask about this in #travis.

**Comment by pharpend** [comment]
The error looks like the key is encrypted and needs a passphrase to be decrypted. I would imagine the travis server has its own ssh key, couldn't you add that to the ~/.ssh/authorized_keys ? That way, we wouldn't need to provide our own key in the repo?

**Comment by pharpend** [comment]
I see that this eliminates one of the errors, but there's still the issue listed above. This is nonetheless a good pull request, so I'm merging it.

**Pull request merged**
