### PR TITLE
Add details on dependencies and link to build system in README

### PR DESCRIPTION
**Pull request by wei2912**
This solves part of https://github.com/learnmath/lysa/issues/63.

### CODE REVIEW

**Comment by pharpend** [comment]
I'll merge this, but, in the future, please follow the guidelines for line length. I realize now that those aren't documented anywhere. I shall open an issue.

I don't know what editor you are using, but in vim, you can run `gqq` to break up a line, and `<n>gqq` to break up `<n>` lines. In Emacs, you can run `M-q` to break up a paragraph or region.

**Comment by pharpend** [comment]
Actually, no, this is wrong. The contributiing guide now has marginally more formal lists of dependencies.

> ### TeXLive
> 
> TeX is the markup language in which LYSA is written, so you need a TeX
> distribution to compile it. Note that if you are only interested in the PDF
> file, we publish regular builds [here](http://184.164.72.39/lysa/). The target
> TeX distribution is [TeXLive][texlive], but it probably works on other TeX
> distributions. Below you can find installation instructions for select operating
> systems. If you don't see your operating system there, but know what software is
> needed, please add it and send a pull request.
> 
> #### Gentoo
> 
> **Warning**: this will spawn a ton of processes, but will make the build a lot
> faster (from several hours to a few minutes). If your memory is precious, use
> `-av` instead of `-jav`.
> 
> ```
> # emerge -jav dev-tex/biblatex dev-texlive/texlive-latexrecommended dev-texlive/texlive-xetex
> ```
> 
> #### Ubuntu 12.04
> 
> ```
> # apt-get install biblatex texlive texlive-latex-extra texlive-bibtex-extra texlive-xetex texlive-math-extra texlive-latex3
> ```
> 
> [texlive]: https://www.tug.org/texlive/

**Comment by wei2912** [comment]
Ooh, didn't see that. Updating my guide. Any idea about the 80-char wrap in Sublime Text? If not, I'll just work in vim.

**Comment by pharpend** [comment]
> Any idea about the 80-char wrap in Sublime Text?

No, I use Emacs.

**Comment by pharpend** [comment]
Awesome, merging!

**Pull request merged**
