### PR TITLE
Add list of main contributors to LYSA.

### PR DESCRIPTION
**Pull request by wei2912**
An issue was created for this at https://github.com/learnmath/lysa/issues/24.

### CODE REVIEW

**Comment by pharpend** [comment]
You should include emails and irc nicks for everyone.

**Comment by pharpend** [comment]
Well then. Why'd the build fail? I'll look in a minute, my laptop is at 3% battery charge.

**Comment by wei2912** [comment]
Build errored out because it attempted to deploy. Fixing this.

**Comment by pharpend** [comment]
I'll merge when the build succeeds.

**Comment by wei2912** [comment]
The build will succeed if merged into the repository, but not as a PR. That's for a seperate issue. (https://github.com/learnmath/lysa/pull/28)

**Pull request merged**
