### PR TITLE
Pay our dues to LYAH.

### PR DESCRIPTION
**Pull request by pharpend**
I guess this accidentally got removed. Even if LYAH leaves a bit to be desired,
it is the motivation and namesake for the book, so we have to mention it.

### CODE REVIEW

**Comment by ghost** [comment]
I'm fine with a nod to LYAH, but it breaks the flow here. Why doesn't it get its own page right at the start?

**Comment by pharpend** [comment]
@beingbrown could you elaborate?

**Comment by ghost** [comment]
It breaks the flow in the 'conversation' happening in chapter 1. Instead, maybe it should get a mentionon the acknowledgements page or as 'front matter'

**Comment by pharpend** [comment]
Hmm. What's clear today is that we need an acknowledgements section. I'll go ahead and create one.

**Comment by pharpend** [comment]
Okay, I did the merge on my end, and moved the LYAH stanza to the acknowledgements section. @beingbrown you can merge this now.

**Pull request merged**
