### PR TITLE
Use latexmk for building the pdf

### PR DESCRIPTION
**Pull request by daniel-j-h**
This changes the build system from the build script to a makefile using latexmk for building the pdf.

In theory you could make the engine user-specific.
I successfully compiled the pdf using lualtex instead of xelatex as engine.

Now latexmk handles dependencies, takes care of invoking the engine the correct number of times, and so on. Unfortunately latexmk generates a lot of garbage files in doing so, but you could specify a outdir for this.
For now I added those files to the gitignore and the makefile's clean target.

Note: include paths now have to be directory-prefixed; alternatively see e.g. \graphicspath)

(I also had to adapt the bib entry in doing so, because I was getting an error of "too many commas in name", so I grabbed the correct bibtex.)

### CODE REVIEW

**Comment by wei2912** [comment]
`.travis.yml` should be edited to run `make` instead. That way we can see if the Travis CI build succeeds.

**Comment by daniel-j-h** [comment]
Sorry for that. I added the latexmk dependency and changed the command to make.

(Was unable to check with travis-ci, though)

**Comment by pharpend** [comment]
Yeah, definitely work out the stuff with travis first. I won't merge this, and I don't think @wei2912 will unless you've already dealt with the travis stuff. Particularly because _I_ don't want to deal with the travis stuff.

@beingbrown Would you maybe add a thing to the contrib guide about dealing with Travis? @wei2912 might be able to help you there, as he was the one to set it up.

**Comment by wei2912** [comment]
The Travis stuff should work in theory. Merging might be complicated, so I'll do the merge.

EDIT: Nvm, I see that https://github.com/learnmath/lysa/issues/19 has to be fixed first.

**Comment by pharpend** [comment]
Let me do the merge, I want to make sure the garbage files are handled
correctly

**Comment by wei2912** [comment]
Sure. :)

**Comment by ghost** [comment]
@pharpend I'm going to open an issue on it and tag you and @wei2912

**Comment by pharpend** [comment]
I'm rejecting this, for the following reasons:
- It creates junk files. It's good to ignore them, but that's not good enough. You also need to write a script to sandbox & delete them.
- It breaks the file hierarchy, so you would have to go into the chapters and change each of them.
- The build fails if there are undefined references. This is unacceptable, as we often include references to work we haven't done yet.
- It doesn't provide much in the way of advantages.

**Comment by daniel-j-h** [comment]
Re. junk files: make clean does this; it's not hard to invoke this target after building the pdf.
latexmk -c leaves the pdf behind. There's even a switch to use a temp. directory.

I don't understand your point about the file hierarchy. Instead of the build script's cp of all tex files into a single directory, you just specify the directory they are in in the include directive. This reflects the real document structure, e.g. "chapter/First.tex" instead of "First.tex" when this file is in reality in the chapter directory.

Undefined bibtex references? Or undefined tex files? In both cases, how hard is it to create an empty tex file or empty bibtex entry? Failure in case of undefined references is what you want for your pdf.

The advantages of latexmk are clear once it gets more complicated.
For example dependencies because of makeindex, makeglossaries, bibtex, in what order and how often to invoke your latex engine, bibtex and so on.

Even for "simple" projects you have to invoke your latex engine multiple times, to (1) resolve all references, (2) insert them and then (3) change the layout with the newly inserted references.

I'm fine with you rejecting this pull request -- it's your project after all.
But please don't refuse to learn about the issues it solves.

> ftp://ftp.rrzn.uni-hannover.de/pub/mirror/tex-archive/support/latexmk/latexmk.pdf

**Comment by pharpend** [comment]
I understand the advantages, but the advantages are minimal next to the problems it creates.

**Comment by wei2912** [comment]
The old script creates junk files in the process, too. We just included a clean step in the script itself (and ignored the build file). It's trivial to do a `make clean` after the build and should be a habit that everyone learns to take up.

I see no issues with the file hierarchy. The current build script does it in a very poor way, by copying all the files into a folder. This would be a welcome change to our current system.

The failure of the build for undefined references isn't a major issue. It can (and should) be solved by creating an outline.

On the other hand, I feel that the maintainability of this solution is a major advantage and can help us organize our files better.

**Comment by pharpend** [comment]
> We just included a clean step in the script itself (and ignored the build file). It's trivial to do a make clean after the build and should be a habit that everyone learns to take up.

That's true, but you're forgetting something. This change would create more work for me, while creating no actual advantage (beyond some theoretical thing about dependency management, which we already handle in a different manner).

> I see no issues with the file hierarchy. The current build script does it in a very poor way, by copying all the files into a folder.

I disagree. I structured the copying that way specifically so everything would be in the same directory. Not having to specify the folder means less typing for me, which means fewer errors.

> The failure of the build for undefined references isn't a major issue. It can (and should) be solved by creating an outline.

Yes it is, and no it won't. This is again the case of this change providing more work for me while providing no discernible advantage.

> On the other hand, I feel that the maintainability of this solution is a major advantage and can help us organize our files better.

Nobody has made a good case explaining why this solution is more maintainable than my current solution.

**Comment by wei2912** [comment]
I'll leave that to @daniel-j-h to discuss about maintainability. I find that shell scripts get messy quickly when used for building.

**Comment by pharpend** [comment]
Oh, I'm sure. I have no problem switching to makefiles sometime in the future. However, this proposed solution was just terrible. If someone would write a makefile which had all of the supposed benefits of this patch, but didn't create any extra work for me, I'd be open to it.

**Pull request closed without merging**
