### PR TITLE
Some edits to the readme.

### PR DESCRIPTION
**Pull request by pharpend**

### CODE REVIEW

**Comment by pharpend** [comment]
Lemme make one more change.

**Comment by pharpend** [comment]
Alright, ready to merge.

**Comment by wei2912** [comment]
Next time, append [ci skip] to the end of these commit messages, so that Travis doesn't build them.

**Comment by wei2912** [comment]
Thanks for this.

**Comment by jesyspa** [comment]
Why in the world do people need our location?

**Comment by pharpend** [comment]
So they know when we might be on IRC.

**Pull request merged**
