### PR TITLE
Chapter 2.1: Intuition of a Set

### PR DESCRIPTION
**Pull request by wei2912**
I added solutions to the exercises, as well as details on intersects. Please review for any inaccuracies. Thanks!

### CODE REVIEW

**Comment by pharpend** [comment]
Thanks for doing this, I will review when I get more coffee in me.

**Comment by wei2912** [comment]
There may be too few exercises & solutions for intersects. You may wish to add some more.

**Comment by pharpend** [comment]
As with #65, could you fix the line length stuff?

**Comment by wei2912** [comment]
Fixed that.

**Comment by pharpend** [comment]
I don't like your answers to the exercises, but they are better than no answers. Merging.

**Comment by wei2912** [comment]
I couldn't quite figure out how they should be worded, so I made them concise. Hopefully someone can expand on it.

**Comment by pharpend** [comment]
That's what I'm thinking.

**Pull request merged**
