### PR TITLE
Ignore `book/tmp`.

### PR DESCRIPTION
**Pull request by wei2912**
Title says it all.

### CODE REVIEW

**Comment by pharpend** [comment]
The script should delete the directory when it terminates. If it's not doing that, pull from my branch, I'm not sure I've merged that into the lm tree:

https://github.com/pharpend/lysa/blob/f/peano/book/build

See if the problem persists afterward

**Comment by wei2912** [comment]
True, I forgot about that. Well, if the script fails halfway, it won't be removed.

**Comment by pharpend** [comment]
The updated script in #17 does. I merged it into the build-system branch, waiting for @beingbrown to merge it into the develop branch.

**Comment by pharpend** [comment]
Alright, I'm going to close this request, because it's no longer an issue.

**Pull request closed without merging**
