### PR TITLE
Build script now terminates on error.

### PR DESCRIPTION
**Pull request by pharpend**

### CODE REVIEW

**Comment by pharpend** [comment]
@beingbrown I done goofed, and accidentally kicked you out of the repo, and thus can't assign you the issue. I invited you back, but until that happens, here's my impromptu method of assigning you to the issue.

**Comment by pharpend** [comment]
Well never mind, apparently I accidentally merged this.

**Comment by wei2912** [comment]
The build script should also do `exit 1` on a failure, which Travis relies on to figure out if our build is failing. Otherwise the fancy icon on our README is misleading. :(

**Comment by pharpend** [comment]
@wei2912 Actually, it doesn't matter, because the build will fail if the TeX compile takes too long. The TeX compile doesn't fail, instead it prompts the user for possible fixes, which is annoying. I'm sure there's a way to turn this off, _then_ this will be an issue.

**Comment by wei2912** [comment]
@pharpend True, but I still think it'd be best to include an `exit 1` statement, just in case some building mechanism we use in the future doesn't prompt for input.

**Comment by pharpend** [comment]
Alright. Would you do the change & PR? I'm working on content right now.

**Comment by pharpend** [comment]
Yes, I agree, especially if we end up merging #20

**Pull request merged**
